// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsAzGFE_fBcgvgXhYqM9ahcbnwkOdpx1E',
    appId: '1:330143337990:android:7d5bdb249d8c79fd813d87',
    messagingSenderId: '330143337990',
    projectId: 'task-8e468',
    storageBucket: 'task-8e468.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC0iFBMKz2o8jFWjvwoSBEQoy-2TO2tcE',
    appId: '1:330143337990:ios:6db05a404c0d0cd6813d87',
    messagingSenderId: '330143337990',
    projectId: 'task-8e468',
    storageBucket: 'task-8e468.appspot.com',
    androidClientId: '330143337990-87p21p3u3qpfj0gosa7hqeijoajf96b4.apps.googleusercontent.com',
    iosClientId: '330143337990-om5cavtfdt02jtv83r26v6lp4tv19e5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasks3',
  );
}
